### ISSUE TITLE
DSL grammar

### ISSUE THREAD

**Issue by marquesarthur** [therealAJ/dsl-charts#1]
Hi everyone,

Would be so kind and add an example of the DSL in either your README file or as another markdown file. I want to double check your DSL idea and ensure that you are on the right path.

Thanks in advance,
Arthur

**Comment by daylanrobertson** [comment]
Please see input.txt in root directory for sample input.

**Comment by marquesarthur** [comment]
Awesome work thus far!
Question to reflect on:

- How do you handle several items?
- Can you build two different charts using the same data?

**Comment by kgrover97** [comment]
Implemented variables to remove duplication of data. and make creating multiple graphs easy.
